# Generated by Django 6.0.6 on 2026-06-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
            ],
        ),
    ]
